### ISSUE TITLE
package mProject of Montage

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/Stimela-classic#790]
For Caracal we need mProject to be packaged into stimela. We need it because mProjectCube does not properly work in regridding 2D masks, which are the ones needed for self-cal cleaning.

Originally raised here: https://github.com/caracal-pipeline/stimela/issues/226

**Comment by Fil8** [comment]
cool!. The module to be packaged is `mProject`. In stimela there are two other modules of montage already packaged `cabs/mProjectCube` and `cabs/montage`. The first is to regrid cubes the second is to mosaic. 

http://montage.ipac.caltech.edu/docs/mProject.html is the function we need for regrid 2d

**Comment by Athanaseus** [comment]
@Fil8, please checkout branch `add_montage_mProject`.
or `pip install -U git+https://github.com/ratt-ru/Stimela-classic.git@add_montage_mProject`
